### ISSUE TITLE
Beta editor not loading in Safari browser

### ISSUE THREAD

**Issue by microbit-giles** [Microsoft/pxt-microbit#1278]
**Describe the bug**
Current version of Beta editor will not load in Safari.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Click 'Allow' when asked if it can access disk space.
3. See the dark screen below with animated logo, page never loads.

**Expected behavior**
Expected editor to load as it does in Chrome.

**Screenshots**
<img width="740" alt="screen shot 2018-09-21 at 08 21 43" src="https://user-images.githubusercontent.com/42380137/45866152-c5144d00-bd77-11e8-8c50-998b5072d083.png">

**Desktop (please complete the following information):**
 - OS: OS X High Sierra 10.13.4 (17E199)
 - Browser: Safari
 - Version 11.1 (13605.1.33.1.2)

**Smartphone (please complete the following information):**
not tested

**Additional context**
Safari browser is *not* in Private browsing mode.

**Comment by microbit-mark** [comment]
@microbit-giles Does updating the OS/Safari fix it? I'm on 10.13.6 and Safari 12 and don't get the issue.

**Comment by microbit-giles** [comment]
I just updated to 10.13.6 but wasn't offered a Safari update to version 12, now on Safari Version 11.1.2 (13605.3.8), problem persists. I'm confused as my system says it it now up-to-date, unclear how to get Safari 12.

**Comment by microbit-rosslowe** [comment]
Cannot replicate on browserstack:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/30410608/45881592-809ea680-bda3-11e8-91a7-6a73e54d45e3.png">

<img width="295" alt="image" src="https://user-images.githubusercontent.com/30410608/45881618-94e2a380-bda3-11e8-8da0-93010a864db6.png">


This is on High Sierra

**Comment by martinwork** [comment]
macOS 10.13.6 Safari 11.1.2 (13605.3.8)

It worked for me until I did Safari/Clear history.  Now it's stuck with the cookie banner  plus grey screen with white microbit and no MakeCode website visible behind.

**Comment by martinwork** [comment]
I visited other MakeCode versions and it unblocked. Can't make it go wrong again.

**Comment by microbit-giles** [comment]
Very odd - Magda has the same problem as me, will find out what version of Safari she is using.

**Comment by microbit-giles** [comment]
@microbit-rosslowe Have you tried the beta editor on Browserstack?

**Comment by abchatra** [comment]
Can you try F12 and share the errors?

**Comment by microbit-giles** [comment]
Javascript console shows this:
<img width="1345" alt="screen shot 2018-09-21 at 15 10 39" src="https://user-images.githubusercontent.com/42380137/45886256-9b2b4c80-bdb0-11e8-9b06-e5c17ae9e0b2.png">

**Comment by pelikhan** [comment]
The WebSQL database is full. Looks like we don't handle well this case. @abchatra we should fix this.

**Comment by microbit-giles** [comment]
I clicked on Develop > Empty Caches and restarted Safari, problem persists.

**Comment by abchatra** [comment]
Should be fixed now.
