### ISSUE TITLE
OLED12864_I2C extension not work in MakeCode V2

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#2215]
In MakeCode V2, when add OLED12864_I2C extension and download to microbit, microbit will show error code 022.

Same program is work in MakeCode V1.

**Comment by pelikhan** [comment]
Use the hex literal to encode the font into a buffer storred in flash.

   const font = hex `02abc....`;

________________________________

**Comment by shaoziyang** [comment]
I tried this method, but it didn't work. It seems that extension have use a big buffer (1025 bytes) cause memory error.

**Comment by pelikhan** [comment]
Did you use a single hex buffer?

**Comment by shaoziyang** [comment]
Yes, I use single hex buffer for **font**, but get same error. When I reduce buffer size for **_screen** (it will loss of data), it will work.

https://github.com/makecode-extensions/OLED12864_I2C

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
I'm looking into fixing the buffer size issue.

However, you should still use a hex buffer for font - this will save 0.5k of memory for other uses. Let me know if you need more info on how to use the hex buffer for font.

**Comment by shaoziyang** [comment]
I test it in pxt version 2.1.1, it still doesn't work and show error code 022.

**Comment by pelikhan** [comment]
The fix is not live yet.

________________________________

**Comment by darzu** [comment]
I've confirmed this appears fixed in /beta https://makecode.microbit.org/_FsxCaU8tKbK8

@shaoziyang , if you have the time, could you try your project as well to make sure the issue is gone in /beta?

**Comment by shaoziyang** [comment]
@darzu Yes, it works now, I will do more test soon.

**Comment by HyperDuino** [comment]
I just tried but still get 022 error.  https://makecode.microbit.org/_hvLA8yV1PfAY

**Comment by shaoziyang** [comment]
@HyperDuino You need run it in MakeCode beta now. 

https://makecode.microbit.org/beta

I am working in new version of OLED12864, with 6x8 font, and quick display speed.

**Comment by abchatra** [comment]
Fixed
