### ISSUE TITLE
There shows forever2 after dragging forever from the toolbox

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2649]
**Describe the bug**
There shows forever2 after dragging forever from the toolbox

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click New Project
3.Dragging **run code foreve**r from the toolbox

**Expect behavior**
There shows forever

**Actual behavior**
There shows forever2
![1](https://user-images.githubusercontent.com/59192069/76420866-c14a0f80-63dd-11ea-91b2-2783c8d1be80.gif)

Additional context
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.13
3.Microsoft MakeCode version: 5.35.15

**Comment by pelikhan** [comment]
The toolbox should append "on_" to the generated parameter.

**Comment by pelikhan** [comment]
fixed.

**Comment by Sheila111** [comment]
@pelikhan  This issue still happens sometimes.
![1](https://user-images.githubusercontent.com/59192069/79086554-1081b800-7d6f-11ea-8b92-5ed56bae9c2f.gif)
