### ISSUE TITLE
Command Responder can't load documentation in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2698]
**Describe the bug**
Command Responder can't load documentation in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Blocks To JavaScript-->Command Responder->Show Instructions

**Expect behavior**
Command Responder can load documentation as in English
![image](https://user-images.githubusercontent.com/59192069/78004818-408f8b00-736d-11ea-8fbc-5323f0723169.png)

**Actual behavior**
Command Responder can't load documentation in Chinese
![image](https://user-images.githubusercontent.com/59192069/78004554-d7a81300-736c-11ea-85fe-3518b046dad6.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.34
3.Microsoft MakeCode version: 5.37.5

**Comment by jwunderl** [comment]
should be fixed when translations clear; the \`\`\`package snippet was translated and it broke documentation loading [here](https://crowdin.com/translate/kindscript/5820/en-zhcn#401266); I cleared that translation on crowdin. Leaving this open to remind myself to take a look at if we could nicely handle mistranslated \`\`\`package statements when rendering, and/or at least make the `/---docs#doc:/courses/blocks-to-javascript/writing-code:blocks:live-zh-CN` endpoint try to fall back to `/---docs#doc:/courses/blocks-to-javascript/writing-code:blocks:en` on error

**Comment by jwunderl** [comment]
closing in favor of dup issue as the original problem from this one is fixed at least

**Comment by Sheila111** [comment]
@jwunderl Still not fixed
![image](https://user-images.githubusercontent.com/59192069/117264028-6ac34e80-ae85-11eb-8f27-73f993c34606.png)
