### ISSUE TITLE
The 'PlayList' icon doesn't show in Beta Deep Dive

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3037]
**describe the bug**
The 'PlayList' icon doesn't show in Beta Deep Dive

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Beta Deep Dive->PlayList

**Expect behavior**
The 'PlayList' icon should show normally in Beta Deep Dive, like 'Play List' in Loving Coding
![image](https://user-images.githubusercontent.com/58197774/81789276-52e91100-9536-11ea-9b22-44e2d296e73d.png)

**Actual behavior**
The 'Play List' icon doesn't show in Beta Deep Dive
![image](https://user-images.githubusercontent.com/58197774/81789413-875ccd00-9536-11ea-8446-7108d9d5fcc6.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.54
3.Microsoft MakeCode version: 5.37.66

**Comment by pelikhan** [comment]
@ganicke can you add a playlist screenshot?

**Comment by ganicke** [comment]
Yea, OK.

**Comment by KellyLuo1** [comment]
@pelikhan This bug reproduces again
![image](https://user-images.githubusercontent.com/58197774/84487271-18a79680-acd1-11ea-9790-f41520fc72d6.png)
**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.12
3.Microsoft MakeCode version: 6.0.13

**Comment by ganicke** [comment]
This doesn't repro. Might be cache related...

![image](https://user-images.githubusercontent.com/27789908/84533083-49210d80-ac9c-11ea-8a9c-0c70ce971627.png)

**Comment by pelikhan** [comment]
It should be fixed now.

**Comment by Sheila111** [comment]
@pelikhan @ganicke Still not fixed
![image](https://user-images.githubusercontent.com/59192069/117389539-19679d80-af1f-11eb-8d22-3942c6391af8.png)
