### ISSUE TITLE
Extension does not update localisation

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3265]
**Describe the bug**
In the latest release, adding the Maqueen extension when Chinese Simplified is selected does not update the localisation for the extension

**To Reproduce**
1. Search and maqueen in extensions
2. Switch to Simplified Chinese
3. Look at blocks in extension, they should update with the changed language
4. Blocks are not update

**Expected behavior**
Blocks should update as in previous release makecode.microbit.org/v2

**Screenshots**
makecode.microbit.org

<img width="629" alt="Screenshot 2020-06-12 at 13 58 47" src="https://user-images.githubusercontent.com/31242877/84505286-631b1a00-acb5-11ea-99cf-6962a823c1e3.png">

makecode.microbit.org/v2
<img width="582" alt="Screenshot 2020-06-12 at 13 59 13" src="https://user-images.githubusercontent.com/31242877/84505284-61515680-acb5-11ea-976a-16f2eedc7365.png">

**Comment by abchatra** [comment]
We are on top of this, will address as soon as possible.

**Comment by abchatra** [comment]
Fix here: https://github.com/microsoft/pxt/pull/7180

**Comment by abchatra** [comment]
This is fixed and a hotfix released to microbit editor. Please test.

**Comment by microbit-mark** [comment]
This still reproduces when switching from Chinese to English

1. Open makecode.microbit.org
2. Switch to Chinese simplified language
3. Add maqueen extension
4. switch to English language
5. Open maqueen extension and Chinese translations persist.

![image](https://user-images.githubusercontent.com/31242877/88383194-fb6ee900-cda1-11ea-877e-a3edb97063fd.png)

**Comment by abchatra** [comment]
@microbit-mark  I don't preproduce this issue. It switches correctly.

**Comment by tangjie133** [comment]
But I still have this problem
![QQ截图20200727142956](https://user-images.githubusercontent.com/51323906/88510499-b0f5a280-d015-11ea-84e1-218fef943ab5.png)

**Comment by microbit-mark** [comment]
@abchatra This reproduces for me on Firefox 78 and Chrome 84 MacOS 10.15.6

**Comment by abchatra** [comment]
Does it go away if you refresh?

**Comment by microbit-mark** [comment]
No, tried several refreshes in Chrome

**Comment by MKleinSB** [comment]
Did you try to clean Browsercache?

**Comment by microbit-mark** [comment]
Another example of this https://share.getcloudapp.com/2NuyrLEw clearing the cache has no affect

**Comment by microbit-mark** [comment]
This appears to be fixed so closing
