### ISSUE TITLE
Embedding multiple blocks causes duplication Javascript errors

### ISSUE THREAD

**Issue by jxns** [microsoft/pxt-microbit#3358]
I embedded several simple blocks as described here: https://makecode.microbit.org/blocks-embed

The blocks are rendered as expected but the console is showing a lot of javascript errors:
`
duplicate block definition: math_map
duplicate block definition: math_constrain_value
duplicate block definition: device_build_image
pxtembed.js:148186 duplicate block definition: device_build_big_image
pxtembed.js:148186 duplicate block definition: device_show_image_offset
pxtembed.js:148186 duplicate block definition: device_scroll_image
pxtembed.js:148186 duplicate block definition: device_show_leds
duplicate block definition: device_print_message
....
`

Its throwing around ~170 errors in total. This is only occuring when using multiple `<pre>` code-blocks on a site. There are no errors when using just a single `<pre>`-block.

Any suggestions or fix for that?

**Comment by abchatra** [comment]
This should be fixed now. If not please share your code.

**Comment by baa-mb** [comment]
Please it is not fixed, when I change to another language like german: than rendering of block is producing lot of console errors and it slow down massive.
if you need a screen shot - please  give me a tip.

```blocks
basic.showNumber(22)
```

is producing no error, if you are in language englisch, but it hat lots of errors in german, ...
<img width="1907" alt="z-Bild 2021-06-16 um 20 27 22" src="https://user-images.githubusercontent.com/34665120/122426206-5730fa80-cf90-11eb-8f28-936f4d8a2c10.png">

**Comment by abchatra** [comment]
I can reproduce this issue.

**Comment by abchatra** [comment]
Fixed
