### ISSUE TITLE
Users accidentally hitting https://makecode.microbit.org/v2

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3829]
> micro:bit support: 42252

**Describe the bug**
Presumably through Google search, people are hitting https://makecode.microbit.org/v2 by accident thinking it is the micro:bit V2 editor. Searching for "makecode microbit v2" reveals this as the top result.

![5F6456D5-69E5-4BBB-90FD-BCA735C8EEBE](https://user-images.githubusercontent.com/31242877/103911353-d119a980-50fd-11eb-8d44-7f69412d423b.jpg)

I believe we've had a couple of people ask about this, but is causing confusion as downloading and flashing files results in an error.

**Additional context**
Google offer a way to remove the result https://support.google.com/webmasters/answer/9689846#block_content

We have this issue with the Python Editor too in https://python.microbit.org/v/2.0  and have placed a banner on top to direct people to the live editor

**Comment by jaustin** [comment]
@abchatra we see people getting confused by this - anything you can manage at your end?

**Comment by abchatra** [comment]
This should be doable. I will schedule someone from my team to take a look.

**Comment by abchatra** [comment]
We need to fix this.

**Comment by abchatra** [comment]
Fixed

**Comment by shakao** [comment]
robots.txt is correctly updated, but the url is still showing up in search results, so i also submitted a temporary removal request via the google search console, which should hopefully drop it out of the results (and then it won't be re-crawled)
