### ISSUE TITLE
Mac: Mouse focus changed when dragging code from toolbox

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4060]
**Describe the bug**
**Mac:** Mouse focus changed when dragging code from toolbox

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Dragg code from toolbox and observe **mouse focus** 

**Expect behavior**
Mouse focus won't change when dragging code from toolbox
![2](https://user-images.githubusercontent.com/59192069/118214488-65c45780-b4a2-11eb-9039-e37cf0cbe2f5.gif)

**Actual behavior**
**Mac:** Mouse focus changed when dragging code from toolbox
![1](https://user-images.githubusercontent.com/59192069/118214393-34e42280-b4a2-11eb-84c8-74cd8c6f9a79.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.81
3.Microsoft MakeCode version: 6.13.29

**Comment by abchatra** [comment]
Probably fixed with latest update.

**Comment by livcheerful** [comment]
@jwunderl tested this for me on his Mac, and looks like Monaco 0.24.0 doesn't fix this - but he also says it doesn't feel TOO too weird

**Comment by jwunderl** [comment]
To summarize current behavior; if the last line is empty and you drag into the space below any monaco lines, it bumps the cursor up to the beginning of the first line. If the last line has any content in it (even whitespace) then it moves cursor to the closest character (that is, it acts as if the y position of the mouse is on the line itself).

The first case feels a bit buggy / ideally it would all behave consistently as the second case, but it doesn't feel urgent to me - I personally expect to drag the snippet to where I want it to go in the first place. I'm not really sure what the expected behavior when you drag the snippet below the workspace is in the first place, besides possibly 'insert as new last line".

**Comment by abchatra** [comment]
@Nina-1210 can you test this and let us know if this is fixed not.

**Comment by Nina-1210** [comment]
@abchatra, verified the issue on latest beta build **7.1.48**, it has been fixed on the Mac platform by using Safari browser.

**Screen Recording:**
https://github.com/user-attachments/assets/885e7149-a036-4e10-ab14-4bc414b9f815
