### ISSUE TITLE
Simulator crashes with native extension

### ISSUE THREAD

**Issue by philipphenkel** [microsoft/pxt-microbit#4292]
**Describe the bug**
The latest public editor fails to integrate the simple native library 
 https://github.com/philipphenkel/pxt-buttons with `Simulator crashed, no error handler TypeError: Cannot read property 'disable' of undefined.` Compilation works as soon as you do whitespace changes to the code. See animated gif.

**To Reproduce**
1. Go to https://makecode.microbit.org/_JwdhzeCu27Pw
2. Open the code editor
3. Compiles with error "Cannot read property 'disable' of undefined"

**Workaround**
4. add a blank line to get rid of the compilation error

**Expected behavior**
Compiles without error form the beginning.

**Screenshots**
![Jul-26-2021 19-59-50](https://user-images.githubusercontent.com/828416/127036487-57695def-2199-42a2-855f-e136d0894b2c.gif)

**micro:bit version (please complete the following information):**
code runs both on v1 and v2. buttons.disable() disable the microbit buttons on v2 devices.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version 91.0.4472.114

**Additional context**

**Comment by abchatra** [comment]
This is a runtime exception in the simulator.

We don't have support for C++ extensions in the simulator (not possible to run C++ code in the browser as we have javascript VM).  Exception goes away when you add new line because we clear on every edit of the file. If you run the simulator issue exception will reappear.

We can't address this issue.

**Comment by philipphenkel** [comment]
@abchatra I have other extensions with C++ code that work well, e.g. https://github.com/philipphenkel/pxt-serial-read. Did MakeCode drop the support recently? I hope not.

To more specific about the problem here: I don't expect the browser to run C++ code (the C++ part works well on the microbit). Instead, I added a shim which does nothing (empty function). Saying that, I could try adding some useless code to the shim. Maybe the problem is, that the browser removes empty code blocks.

**Comment by abchatra** [comment]
Oh yes, that should work. I am reopening this. However if you find the reason let me know. pxt-serial-read seems to work fine.

**Comment by philipphenkel** [comment]
Once again, another sleep fixed the problem ;-) 

Seriously, the workaround is to add some code to the shim. The shim below is working. If basic.pause is removed and the function turned into a Nulloperation, you will get the simulator crash.

```
    /**
    * Enable the micro:bit buttons. 
    */
    //% shim=buttons::enable
    export function enable(): void { basic.pause(100) }
```

Even though I'm happy with my workaround, I recommend fixing it. It could save quite some time for the next extension developer - especially for those who are new to shims at all.

**Comment by abchatra** [comment]
Good feedback @philipphenkel  I will keep the bug open.

**Comment by abchatra** [comment]
@tianli can you provide a shim for your C++ similar to what suggested by philip above and see?
   /*
    * Enable the micro:bit buttons. 
    */
    //% shim=**NAMESPACE**::**METHOD_NAME**
    export function METHOD_NAME(): void { basic.pause(100) }

**Comment by tianli** [comment]
@abchatra Created a pull request to update our version. Please approve, thanks!

**Comment by tianli** [comment]
@abchatra Sorry, but the previous version has some typescript errors. Could you help update the version again? Thanks!

**Comment by tianli** [comment]
Thanks for the push! @abchatra . However we still see the simulator crash error. (https://makecode.microbit.org/32247-58873-15224-33481)

pxtsim.js:1 Simulator crashed, no error handler TypeError: Cannot read properties of undefined (reading 'begin')
    at Object._main___P3268 [as fn] (eval at Runtime (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:79866), <anonymous>:71:25)
    at loop (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:77294)
    at topCall (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:78365)
    at Runtime.run (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:79904)
    at https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:34970
loop @ pxtsim.js:1
topCall @ pxtsim.js:1
Runtime.run @ pxtsim.js:1
(anonymous) @ pxtsim.js:1
Promise.then (async)
l @ pxtsim.js:1
i @ pxtsim.js:1
pxtapp.js:1 DBG-MSG breakpoint {type: 'debugger', subtype: 'breakpoint', breakpointId: undefined, globals: {…}, stackframes: Array(1), …}breakpointId: undefinedexceptionMessage: "Cannot read properties of undefined (reading 'begin')"exceptionStack: "TypeError: Cannot read properties of undefined (reading 'begin')\n    at Object._main___P3268 [as fn] (eval at Runtime (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:79866), <anonymous>:71:25)\n    at loop (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:77294)\n    at topCall (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:78365)\n    at Runtime.run (https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:79904)\n    at https://pxt.azureedge.net/blob/4d2d8d7e0317df99b786e40760f31a769b6d0aea/pxtsim.js:1:34970"globals: {}stackframes: [{…}]subtype: "breakpoint"type: "debugger"[[Prototype]]: Object
pxtapp.js:1

**Comment by tianli** [comment]
@abchatra , please help! Thank you!

**Comment by abchatra** [comment]
Sure I will take a look tomorrow.

**Comment by abchatra** [comment]
@tianli you have two files with the same code shim.d.ts and shim.ts. shim.d.ts is the one getting picked up and it doesn't have the default code.

**Comment by tianli** [comment]
OK, changed back to put everything in shim.d.ts. https://github.com/mu-opensource/pxt-muvision/blob/master/shims.d.ts Please take a final look before creating the release. @abchatra Thanks a lot!

**Comment by abchatra** [comment]
This issue is fixed.

**Comment by abchatra** [comment]
Oh following needs fixing still

_Seriously, the workaround is to add some code to the shim. The shim below is working. If basic.pause is removed and the function turned into a Nulloperation, you will get the simulator crash.

    /**
    * Enable the micro:bit buttons. 
    */
    //% shim=buttons::enable
    export function enable(): void { basic.pause(100) }
Even though I'm happy with my workaround, I recommend fixing it. It could save quite some time for the next extension developer - especially for those who are new to shims at all._

**Comment by tballmsft** [comment]
@martinwork  - sorry - I am reopening as problem is still there - I am not sure it is the same. Will need to investigate more

**Comment by tballmsft** [comment]
Yes - that was the problem. Sigh...

**Comment by tballmsft** [comment]
@abchatra - this is biting me bad on pxt-arcadeshield

**Comment by tballmsft** [comment]
I can see what the problem is. When there is no function implementation, the STS code gets copied like this, as if it were "real" JavaScript
```
    s.tmp_0 = screensim.ScreenState.setPalette();
```
The above fails at runtime. When there is a function body, the STS is correctly flattened like this:
```
    s.tmp_0 = screensim_ScreenState_setPalette__P1290_mk(s);
```

**Comment by abchatra** [comment]
@tballmsft can you add a fake sim body for now as a workaround?

**Comment by tballmsft** [comment]
yes, there are many such changes needed...

**Comment by tballmsft** [comment]
and I seem to have encountered a blocking issue... will need to consult with the team ASAP.
