### ISSUE TITLE
Art for new recording extension

### ISSUE THREAD

**Issue by srietkerk** [microsoft/pxt-microbit#5000]
There is a new extension where students can use the micro:bit microphone to record audio clips. We want the picture that represents the extension to better reflect what the extension will add to a student's project. 

This is the current picture for the extension card:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/49178322/226747709-8dec920c-a558-4b6c-a181-ef44baa191bd.png">

Pictures for these extension cards should be 320x240 in dimension. This would be great to have for the upcoming release April release.

**Comment by abchatra** [comment]
@jaustin Can we please get art for atleast this extension asap?

**Comment by abchatra** [comment]
Still waiting for the art.

**Comment by abchatra** [comment]
Proposed images attached [MakeCodeExt_Thumbnails.zip](https://github.com/microsoft/pxt-microbit/files/11729511/MakeCodeExt_Thumbnails.zip)

**Comment by abchatra** [comment]
Fixed

**Comment by jaustin** [comment]
Still seeing the old image on /beta but there are updates on the other. Maybe this is known but thought I'd mention in case this is expected fixed

**Comment by abchatra** [comment]
Check now.
