### ISSUE TITLE
Errors loading the Beta editor 

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5526]
**Describe the bug**

The beta editor seems to work in an incognito window, but in some existing sessions it shows errors to multiple different people.

Some of the issues found with different browser sessions:

### Carlos' computer Chrome
Trying to load an existing project from the front page:
https://makecode.microbit.org/beta
<img width="322" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/5b11c446-01d1-4bdf-9f62-9b59fa5d65eb">

Trying to load the beta editor:
https://makecode.microbit.org/beta#editor
<img width="75%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/473565ae-2a3b-49e9-90d3-d58ade75c1cb">
Same browser with the debug flag: https://makecode.microbit.org/beta?dbg=1#editor
<img width="75%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/570e4b7a-82b3-4a59-95b6-a536b88453d2">

### Carlos' computer Edge
On the same computer with a different browser (which had used makecode and makecode beta before):
<img width="75%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/a73944b9-1c47-4cfe-9912-fa777d3669a0">

### Jonny's computer Chrome
The experimental feature enabled was the accessible blocks
<img width="75%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/95a5b6b5-add8-4c50-aded-5a82b9a5bf4b">

### Katie's computer Chrome

Also accessible blocks experimental feature enabled.

<img width="75%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/02bb2d4e-0f8c-4f51-9008-36b6c03dd82a">

**Comment by microbit-carlos** [comment]
@microbit-katie has found that disabling the accessible blocks experimental feature resolved the issue, so it looks like that might be the culprit.

**Comment by microbit-carlos** [comment]
While disabling the accessible blocks feature resolves the problem when the blocky toolbox and workspace don't load, the issue I still have where projects cannot be loaded at all, still persist.

I can leave this session as it is for the time being in case there is any diagnostic you'd like me to run (the `?dbg=1` flag doesn't seem to do anything). In this state all projects are inaccessible, but I can create new ones that work.

<img width="49%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/c751281a-8896-4b82-96bd-cbc0fd39714a"> <img width="49%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/253db78e-52a2-43ee-9ec1-71b69152f8eb">

**Comment by abchatra** [comment]
@riknoll blockly issue?

**Comment by riknoll** [comment]
I've fixed the keyboard nav bug, just haven't bumped it to beta yet!

I'll look into the other bug...

**Comment by riknoll** [comment]
the keyboard fix is now in beta @microbit-carlos

**Comment by microbit-carlos** [comment]
Were you able to look into the other issue @riknoll ?
I still have the beta session with broken projects, in case it's useful for debugging.

**Comment by riknoll** [comment]
@microbit-carlos oh, no i wasn't able to repro this after fixing the keyboard nav so i assumed it was fixed. is this only an issue with projects you opened while the keyboard nav bug was still there? it's possible that the exceptions caused the project to save in a corrupted state.

**Comment by microbit-carlos** [comment]
Not quite, as it's not only with projects I tried to open with the keyboard nav experiment, but I believe with all existing projects that existed at the time, even the ones I didn't attempt to open.

**Comment by riknoll** [comment]
alright then, can you give me an updated screenshot of your console log?

**Comment by abchatra** [comment]
Original issue is fixed.
