### ISSUE TITLE
iPad: The simulator disappeared once finishing the JavaScript/Python tutorial on iPad vertical screen

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5568]
**Describe the bug**
The **simulator disappeared** once finishing the **JavaScript/Python tutorial** on iPad **vertical screen**
 
**Steps to reproduce the behavior**
1.Navigate to h**ttps://makecode.microbit.org/beta** on iPad.
2.Open a **JavaScript/Python** tutorial on **iPad vertical screen**.
3.Complete the tutorial, click Done.
4.Observe the simulator in the right-down corner.
 
**Actual behavior:**
The simulator disappeared.
 
**Expected behavior:**
There is simulator in the right-down corner.
 
**Screen Recording:**
https://github.com/microsoft/pxt-microbit/assets/148834117/a0dec716-4687-4e83-9462-f82fef3406de

**Workaround:**
Switch iPad to horizontal screen and then switch to vertical screen.
Switch to Blocks editor once finished the tutorial, then revert to JavaScript/Python editor.

**Additional context:**
1.OS: iPad 8th 17.4
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
This bug also reproduced in Windows 11 when size the browser window too small.

**Comment by fionama100** [comment]
I have verified this bug in the lasted version: 7.0.16 for the iPad platform, so I reopen it now.

**Comment by jwunderl** [comment]
We typically close bugs when merged, but there is a bit of a delay between commits being merged and being tagged and published to beta, so typically best to wait for a version or two to be published before verifying; appears fixed in 7.0.17 as expected

**Comment by fionama100** [comment]
@jwunderl Thanks for your information. We will wait for a version or two to be published to if one bug which has been fixed still reproduces on the current version. 
At the same time, I verified this issue on the latest version: 7.0.17 and it has been fixed.
