### ISSUE TITLE
Cloud compiler is down

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5797]
CI builds for [pxt-buildpush](https://github.com/microsoft/pxt-microbit/actions/workflows/pxt-buildpush.yml) are failing.

Testing locally with a C++ extension also fails with a 503 error, [this log](https://makecode.com/compile/d0666bc780afd148845bb241674b97f358cfc3af6b2201bbbc78714c8083da5b.log), and shows part of the HTML error page:
```
waiting 8s for C++ build...
polling C++ build https://makecode.com/compile/d0666bc780afd148845bb241674b97f358cfc3af6b2201bbbc78714c8083da5b.json (attempt #18)
build log https://makecode.com/compile/d0666bc780afd148845bb241674b97f358cfc3af6b2201bbbc78714c8083da5b.log
build failed
Code: 503 / <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: 747474">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="
TypeError: Cannot read properties of null (reading 'length')
    at compressHex (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105209:37)
    at /Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105138:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fillExtInfoAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113773:51)
    at async MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113819:33)
{
  sha: 'd0666bc780afd148845bb241674b97f358cfc3af6b2201bbbc78714c8083da5b'
}
polling C++ build https://makecode.com/compile/3ffa5a19ba08deab0649f93dea7d3fc79e4951e8abbfed13ebdcf0eb1fb039a2.json (attempt #1)
build log https://makecode.com/compile/3ffa5a19ba08deab0649f93dea7d3fc79e4951e8abbfed13ebdcf0eb1fb039a2.log
build failed
Code: 503 / <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: 747474">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="
TypeError: Cannot read properties of null (reading 'length')
    at compressHex (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105209:37)
    at /Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105138:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fillExtInfoAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113773:51)
    at async MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113819:33)
{
  sha: '3ffa5a19ba08deab0649f93dea7d3fc79e4951e8abbfed13ebdcf0eb1fb039a2'
}
pxt_modules/core/math.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
```

Trying to build C++ projects on the editor fails with these console messages ([log](https://makecode.com/compile/29ee6635d7bd7282b977d28d4ee4fbe3b5ed8c12f3283041fac0319a6eaa7d83.log)):
<img width="515" alt="image" src="https://github.com/user-attachments/assets/454aad69-320a-4387-a426-1117c476a61b">

CC @abchatra

**Comment by riknoll** [comment]
This seems to have been caused by the Azure front door outage that happened yesterday. Everything should be working now, but please reopen if it happens again

**Comment by microbit-carlos** [comment]
CI is still not building:
https://github.com/microsoft/pxt-microbit/actions/runs/10266714021/job/28431951490

And still having the same issue building a C++ extension locally.

**Comment by microbit-carlos** [comment]
This was working again this morning (UK time), although I'm still having some issues as described in https://github.com/microsoft/pxt-microbit/issues/5796#issuecomment-2273231450.

**Comment by riknoll** [comment]
alright, i'll investigate!

**Comment by microbit-carlos** [comment]
The cloud compiler is fully down again, building C++ extensions via CLI or projects with C++ extensions fails with 5xx errors:

```
waiting 8s for C++ build...
polling C++ build https://makecode.com/compile/ebd387b66960e94e0486c89311d6a30ec023d5ea72db7d3c60564d56b0b5e7d0.json (attempt #5)
build log https://makecode.com/compile/ebd387b66960e94e0486c89311d6a30ec023d5ea72db7d3c60564d56b0b5e7d0.log
build failed
Code: 502 / <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while ac
TypeError: Cannot read properties of null (reading 'length')
    at compressHex (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105209:37)
    at /Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:105138:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fillExtInfoAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113773:51)
    at async MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/carlos/pxt-banana/node_modules/pxt-core/built/pxt.js:113819:33)
{
  sha: 'ebd387b66960e94e0486c89311d6a30ec023d5ea72db7d3c60564d56b0b5e7d0'
}
pxt_modules/core/math.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
```

<img width="453" alt="image" src="https://github.com/user-attachments/assets/8e583334-ca5f-410c-b29e-95e269ce1267">

**Comment by riknoll** [comment]
I'm filing a ticket against azure support

**Comment by riknoll** [comment]
we ended up bumping up our hosting plan for this, seems like another one of our services was hogging all of the memory and starving the CPP compilation service. looking at the logs over the weekend, it seems like everything is working much more smoothly now. please let me know if you see more issues

**Comment by microbit-carlos** [comment]
Thanks @riknoll! Looks better right now.
I'll close this for now and reopen if we encounter issues again 👍
