### ISSUE TITLE
Unexpected block jump when dragging from the toolbox

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#5998]
**Describe the bug**

**To Reproduce**

(Easier via GIF below)

1. Go to MakeCode, new project
2. Add show string "some long string here" to on start
3. Move forever just to the right of the wider on start block
4. Drag an "on button" block from the toolbox over the workspace
5. Observe that "on start" has jumped right a bit and now overlaps forever

After triggering this once, right-click "Format Code" is one way to be able to trigger it again.

This can be more confusing in large projects when you can come back from working over on the right to find your blocks don't look quite how you left them. Our education team encountered this building example projects.

The longer text is just so you can see the move when the toolbox is open.

Similar feel to #5959, but in that case all the blocks move which isn't so bad. I've encountered both of these issues one after the other which can feel quite odd/broken.

**Expected behavior**
The blocks stay where you left them.

**Screenshots**
![Image](https://github.com/user-attachments/assets/4b2fd296-14c4-4c84-a1a4-da8b9782ba71)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 129.0.6668.101 (Official Build) (arm64)

**Comment by abchatra** [comment]
This is fixed in /beta.

**Comment by martinwork** [comment]
@abchatra This still happens in

makecode.microbit.org version:  [7.1.33](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.1.33)

Microsoft MakeCode version:  [11.4.21](https://github.com/Microsoft/pxt/releases/tag/v11.4.21)


![Image](https://github.com/user-attachments/assets/15547562-026b-47ee-8b4e-cff852ffc921)
