### ISSUE TITLE
pxt-neopixel fails to build

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#848]
ASM is hosted at 
https://github.com/Microsoft/pxt-ws2812b

```
$ pxt build
Using target microbit with build engine yotta
  target: v1.1.26 C:\gh\pxt-microbit
  pxt-core: v3.18.10 C:\gh\pxt
building C:\gh\pxt-microbit\temp\ghpkgs\pxt-neopixel
neopixel.ts(235,13): error TS9200: not enough args for sendBufferAsm
```

**Comment by pelikhan** [comment]
Looks like an issue in test.ts

**Comment by abchatra** [comment]
I am assuming this is fixed. If not please reopen.

**Comment by xmeow** [comment]
![image](https://user-images.githubusercontent.com/3390845/42431460-1b8921fe-8378-11e8-9a95-a42283771828.png)
But still don't work in the editor alpha, even after I cleaned the browser cache.

**Comment by abchatra** [comment]
@xmeow I can't repro this issue. Can you share the your gif with repro steps? Are you trying makecode.mcirobit.org/alpha?

**Comment by xmeow** [comment]
Works fine on another pc, could be some web browser cache problem. Thank you @abchatra, the editor is great.
